export const CREATELISTINGCOMPLETE_REQUEST = "CREATELISTINGCOMPLETE_REQUEST";
export const CREATELISTINGCOMPLETE_SUCCESS = "CREATELISTINGCOMPLETE_SUCCESS";
export const CREATELISTINGCOMPLETE_FAIL = "CREATELISTINGCOMPLETE_FAIL";

export const LISTINGCOMPLETE_REQUEST = "LISTINGCOMPLETE_REQUEST";
export const LISTINGCOMPLETE_SUCCESS = "LISTINGCOMPLETE_SUCCESS";
export const LISTINGCOMPLETE_FAIL = "LISTINGCOMPLETE_FAIL";

export const LISTINGPURCHASEDCOMPLETE_REQUEST = "LISTINGPURCHASEDCOMPLETE_REQUEST";
export const LISTINGPURCHASEDCOMPLETE_SUCCESS = "LISTINGPURCHASEDCOMPLETE_SUCCESS";
export const LISTINGPURCHASEDCOMPLETE_FAIL = "LISTINGPURCHASEDCOMPLETE_FAIL";