export const CREATELISTINGCOMPLETE_REQUEST = "CREATELISTINGCOMPLETE_REQUEST";
export const CREATELISTINGCOMPLETE_SUCCESS = "CREATELISTINGCOMPLETE_SUCCESS";
export const CREATELISTINGCOMPLETE_FAIL = "CREATELISTINGCOMPLETE_FAIL";