export const LISTING_LIST_REQUEST = 'LISTING_LIST_REQUEST';
export const LISTING_LIST_SUCCESS = 'LISTING_LIST_SUCCESS';
export const LISTING_LIST_FAIL = 'LISTING_LIST_FAIL';

export const LISTING_DETAILS_REQUEST = 'LISTING_DETAILS_REQUEST';
export const LISTING_DETAILS_SUCCESS = 'LISTING_DETAILS_SUCCESS';
export const LISTING_DETAILS_FAIL = 'LISTING_DETAILS_FAIL';

export const CREATELISTING_REQUEST = 'CREATELISTING_REQUEST';
export const CREATELISTING_SUCCESS = 'CREATELISTING_SUCCESS';
export const CREATELISTING_FAIL = 'CREATELISTING_FAIL';